name: CD
# The pipeline is triggered on:
#  - Repository Dispatch type of "model is registered"
on:
  push:
  repository_dispatch:
    branches: [ritter-class-deploy]


# Environment variables available to all jobs and steps in this workflow
env:
  REGISTRY_NAME: k8scc01covidmlopsacr
  CLUSTER_NAME: k8s-cancentral-02-covid-aks
  CLUSTER_RESOURCE_GROUP: k8s-cancentral-01-covid-aks
  #MLFLOW_EXPERIMENT_NUM: 1 # 1 for mlops, 2 for newsdata
  MLFLOW_RUN_ID: 116ad70a24fe4350b0ea2d5d70a008ce
  MODEL_IMAGE_NAME: newsdata_classbc_svm_1


jobs:
  deploy_to_qa:
    runs-on: ubuntu-latest
    steps:
    - name: Copy Repository Contents
      uses: actions/checkout@master

    - uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ${{ env.CLUSTER_NAME }}
        resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install Python dependencies
      run: |
        pip3 install requests --upgrade

    - name: Install Python dependencies
      run: |
        pip3 install adal --upgrade

    - name: Obtain JWT token
      env:
        KFP_PIPELINE_NAME: ${{ secrets.KFP_PIPELINE_NAME }}
        KFP_HOST: ${{ secrets.KFP_HOST }}
        RUN_ID: ${{ github.run_id }}
      run: |
        export JWT_TOKEN=$(python3 azure-token.py --tenant ${{ secrets.tenant }} \
                                                  --service_principal ${{ secrets.SERVICE_PRINCIPAL }} \
                                                  --sp_secret ${{ secrets.SERVICE_PRINCIPAL_PWD }} \
                                                  --sp_audience ${{ secrets.SERVICE_PRINCIPAL_AUDIENCE }})
        echo "::set-env name=JWT_TOKEN::$JWT_TOKEN"
      working-directory: pipeline

    - name: Download model
      run: |
        cd $GITHUB_WORKSPACE/containers/seldon-score
        curl -H "Authorization: Bearer ${JWT_TOKEN}" -L '${{ secrets.MLFLOW_URL }}/api/get-artifact?path=model/data/model.h5&run_uuid='$MLFLOW_RUN_ID > model.h5
        #cat model.h5
        # echo "::set-env name=mlflow_run_id::$mlflow_run_id"
      env:
        RUN_ID: ${{ steps.deh.outputs.RUN_ID }}

    - name: Build Scoring image
      run: |
        cd $GITHUB_WORKSPACE/containers/seldon-score
        echo "debug outpout "
        echo "MLFLOW_RUN_ID "$MLFLOW_RUN_ID
        echo "${{ env.REGISTRY_NAME }}.azurecr.io/$MODEL_IMAGE_NAME:${{ github.sha }}", ${{ env.REGISTRY_NAME }}.azurecr.io/$MODEL_IMAGE_NAME:${{ github.sha }}
        echo "$RUN_ID", ${{ github.sha }}
        docker build $GITHUB_WORKSPACE/containers/seldon-score -t ${{ env.REGISTRY_NAME }}.azurecr.io/$MODEL_IMAGE_NAME:${{ github.sha }}
        docker push ${{ env.REGISTRY_NAME }}.azurecr.io/$MODEL_IMAGE_NAME:${{ github.sha }}
      env:
        RUN_ID: ${{ steps.deh.outputs.RUN_ID }}

    - name: Promote model to Staging
      run: |
        body=$(curl -H "Authorization: Bearer ${JWT_TOKEN}" ${{ secrets.MLFLOW_URL }}/api/2.0/preview/mlflow/model-versions/search?filter=run_id%3D%27${MLFLOW_RUN_ID}%27 | jq '.model_versions[0] | {name: .name, version: .version, stage: $stage}' --arg stage Staging --compact-output)
        curl -H "Authorization: Bearer ${JWT_TOKEN}" -d $body ${{ secrets.MLFLOW_URL }}/api/2.0/preview/mlflow/model-versions/transition-stage

    - run: |
        mkdir -p /home/runner/work/_temp/_github_home/
        cp $KUBECONFIG /home/runner/work/_temp/_github_home/KUBECONFIG

    - name: Deploy Model to SeldonCore
      uses: 'statcan/actions/helm@master'
      env:
        KUBECONFIG: /github/home/KUBECONFIG
      with:
        release: 'seldon-score'
        namespace: 'serving'
        tillerNamespace: 'serving'
        chart: './containers/seldon-score/chart'
        token: '${{ github.token }}'
        # below we are overwriting the default helm chart values.yml params
        values: |
          image:
            repository: "${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.MODEL_IMAGE_NAME }}"
            tag: "${{ github.sha }}"
          imagePullSecrets:
            - name: k8scc01covidmlopsacr-registry-connection

    #- name: Setup tmate session
    #  uses: mxschmitt/action-tmate@v2